# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-07 19:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='Nombre de Categoría')),
            ],
            options={
                'verbose_name_plural': 'Categorías',
                'verbose_name': 'Categoría',
            },
        ),
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_coleccion', models.CharField(max_length=255, verbose_name='Nombre de la Colección')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('cant_favoritos', models.IntegerField(default=0, verbose_name='Cantidad de favoritos')),
            ],
        ),
        migrations.CreateModel(
            name='FotoColeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_coleccion', models.ImageField(upload_to='images/fotos_colecciones', verbose_name='Foto de la Colección')),
                ('coleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado_vindu.Coleccion')),
            ],
        ),
        migrations.CreateModel(
            name='FotoLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_local', models.ImageField(upload_to='images/fotos_locales', verbose_name='Foto del Local')),
            ],
        ),
        migrations.CreateModel(
            name='FotoNovedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_novedad', models.ImageField(upload_to='images/fotos_novedades', verbose_name='Foto de la Novedad')),
            ],
        ),
        migrations.CreateModel(
            name='FotoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_producto', models.ImageField(upload_to='images/fotos_productos', verbose_name='Foto del Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_local', models.CharField(max_length=255, verbose_name='Nombre del Local')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('telefono', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('cant_calificaciones', models.IntegerField(default=0, verbose_name='Cantidad de calificaciones')),
                ('suma_calificaciones', models.IntegerField(default=0, verbose_name='Suma de calificaciones')),
                ('max_dias_retiro', models.IntegerField(default=7, verbose_name='Cantidad máxima de días de retiro')),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='Mail de contacto')),
                ('horario', models.CharField(max_length=255, verbose_name='Horarios')),
                ('latitud', models.FloatField(verbose_name='Latitud')),
                ('longitud', models.FloatField(verbose_name='Longitud')),
            ],
            options={
                'verbose_name_plural': 'Locales',
                'verbose_name': 'Local',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='images/logos', verbose_name='Logo')),
                ('mail_contacto', models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='Mail de contacto')),
                ('porcentaje_vindu', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Porcentaje comisión Vindu')),
                ('cuenta_paypal', models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='Cuenta Paypal')),
                ('mp_client_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mercado Pago Client Id')),
                ('mp_client_secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mercado Pago Client Secret')),
                ('ind_marca_activa', models.BooleanField(default=True, verbose_name='Marca Activa')),
                ('fecha_ultima_actividad', models.DateField(default=datetime.date.today, verbose_name='Fecha de última actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_novedad', models.CharField(max_length=255, verbose_name='Título')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mercado_vindu.Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=255, verbose_name='Nombre del Producto')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('ind_oferta', models.BooleanField(default=False, verbose_name='Producto en Oferta')),
                ('cant_favoritos', models.IntegerField(default=0, verbose_name='Cantidad de favoritos')),
                ('cant_vistas', models.IntegerField(default=0, verbose_name='Cantidad de vistas')),
                ('segmento_edad', models.CharField(choices=[('ADULTO', 'Adulto'), ('NIÑO12', 'Niño de 9 a 12 años'), ('NIÑO5', 'Niño de 5 a 8 años'), ('BEBE', 'Hasta 4 años')], default='ADULTO', max_length=15, verbose_name='Segmento de edad')),
                ('segmento_sexo', models.CharField(choices=[('HOMBRE', 'Hombre'), ('MUJER', 'Mujer'), ('AMBOS SEXOS', 'Ambos sexos')], default='AMBOS SEXOS', max_length=15, verbose_name='Segmento de sexo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mercado_vindu.Categoria')),
                ('coleccion', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='mercado_vindu.Coleccion')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mercado_vindu.Marca')),
            ],
        ),
        migrations.CreateModel(
            name='TagProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Tag')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado_vindu.Novedad')),
            ],
        ),
        migrations.AddField(
            model_name='local',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mercado_vindu.Marca'),
        ),
        migrations.AddField(
            model_name='fotoproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado_vindu.Producto'),
        ),
        migrations.AddField(
            model_name='fotonovedad',
            name='novedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado_vindu.Novedad'),
        ),
        migrations.AddField(
            model_name='fotolocal',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado_vindu.Local'),
        ),
        migrations.AddField(
            model_name='coleccion',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mercado_vindu.Marca'),
        ),
    ]
