# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-09 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coleccion',
            options={'verbose_name': 'Colección', 'verbose_name_plural': 'Colecciones'},
        ),
        migrations.AlterModelOptions(
            name='fotocoleccion',
            options={'verbose_name': 'Imagen de la Colección', 'verbose_name_plural': 'Imágenes de la Colección'},
        ),
        migrations.AlterModelOptions(
            name='fotolocal',
            options={'verbose_name': 'Foto del Local', 'verbose_name_plural': 'Fotos del Local'},
        ),
        migrations.AlterField(
            model_name='fotocoleccion',
            name='foto_coleccion',
            field=models.FileField(upload_to='images/media_colecciones', verbose_name='Imagen de la Colección'),
        ),
    ]
