# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-10 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0002_auto_20180109_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='porcentaje_vindu',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Porcentaje comisión Vindu'),
        ),
    ]
