# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-13 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0004_auto_20180113_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado_vindu.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='TalleProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talle', models.CharField(max_length=30, verbose_name='Talle')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado_vindu.Producto')),
            ],
        ),
    ]
