# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-13 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0005_colorproducto_talleproducto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colorproducto',
            options={'verbose_name': 'Color del Producto', 'verbose_name_plural': 'Colores del Producto'},
        ),
        migrations.AlterModelOptions(
            name='fotoproducto',
            options={'verbose_name': 'Foto del Producto', 'verbose_name_plural': 'Fotos del Producto'},
        ),
        migrations.AlterModelOptions(
            name='talleproducto',
            options={'verbose_name': 'Talle del Producto', 'verbose_name_plural': 'Talles del Producto'},
        ),
    ]
