# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0007_auto_20180117_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotonovedad',
            name='novedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_rel_novedad', to='mercado_vindu.Novedad'),
        ),
        migrations.AlterField(
            model_name='fotoproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_rel_producto', to='mercado_vindu.Producto'),
        ),
    ]
