# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0008_auto_20180118_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combinacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Combinación',
                'verbose_name_plural': 'Combinaciones',
            },
        ),
        migrations.CreateModel(
            name='Foto360Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto360_producto', models.ImageField(upload_to='images/fotos_productos', verbose_name='Foto 360 del Producto')),
            ],
            options={
                'verbose_name': 'Foto 360 del Producto',
                'verbose_name_plural': 'Fotos 360 del Producto',
            },
        ),
        migrations.CreateModel(
            name='TagsProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Tag del Producto',
                'verbose_name_plural': 'Tags del Producto',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='foto_principal',
            field=models.ImageField(default='images/fotos_productos/Sin_imagen_disponible.jpg', upload_to='images/fotos_productos', verbose_name='Foto Principal'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AddField(
            model_name='tagsproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado_vindu.Producto'),
        ),
        migrations.AddField(
            model_name='foto360producto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto360_rel_producto', to='mercado_vindu.Producto'),
        ),
        migrations.AddField(
            model_name='combinacion',
            name='combina_con',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_producto_combinado', to='mercado_vindu.Producto'),
        ),
        migrations.AddField(
            model_name='combinacion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_producto_original', to='mercado_vindu.Producto'),
        ),
        migrations.AlterUniqueTogether(
            name='combinacion',
            unique_together=set([('producto', 'combina_con')]),
        ),
    ]
