# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0009_auto_20180119_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tags',
        ),
    ]
