# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-20 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0010_remove_producto_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagsproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_rel_producto', to='mercado_vindu.Producto'),
        ),
        migrations.AlterField(
            model_name='tagsproducto',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='talleproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talle_rel_producto', to='mercado_vindu.Producto'),
        ),
    ]
