# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import mercado_vindu.models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0011_auto_20180120_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorproducto',
            name='producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='fotoproducto',
            name='foto_producto',
            field=models.ImageField(help_text='Formatos válidos: jpg, jpeg, gif, png', upload_to='images/fotos_productos', verbose_name='Foto del Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15, validators=[mercado_vindu.models.validate_positive], verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0, help_text='El stock del producto', validators=[mercado_vindu.models.validate_non_negative], verbose_name='Stock'),
        ),
        migrations.DeleteModel(
            name='ColorProducto',
        ),
    ]
