# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0012_auto_20180122_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otro_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_producto_otro', to='mercado_vindu.Producto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_producto_original', to='mercado_vindu.Producto')),
            ],
            options={
                'verbose_name_plural': 'Otros Colores',
                'verbose_name': 'Otro Color',
            },
        ),
        migrations.AlterUniqueTogether(
            name='colorproducto',
            unique_together=set([('producto', 'otro_color')]),
        ),
    ]
