# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0007_auto_20180126_1324'),
        ('mercado_vindu', '0013_auto_20180122_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaFavorita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marca_marca_favorita', to='mercado_vindu.Marca')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_marca_favorita', to='auth_api.UserComprador')),
            ],
            options={
                'verbose_name': 'Marca Favorita',
                'verbose_name_plural': 'Marcas Favoritas',
            },
        ),
        migrations.AlterUniqueTogether(
            name='marcafavorita',
            unique_together=set([('usuario', 'marca')]),
        ),
    ]
