# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0016_auto_20180205_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marcaseguida',
            options={'verbose_name': 'Usuario Seguidor de Marca', 'verbose_name_plural': 'Usuarios Seguidores de Marca'},
        ),
    ]
