# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-09 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0009_auto_20180205_1923'),
        ('mercado_vindu', '0017_auto_20180205_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoFavorito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_producto_favorito', to='mercado_vindu.Producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_producto_favorito', to='auth_api.UserComprador')),
            ],
            options={
                'verbose_name': 'Producto Favorito',
                'verbose_name_plural': 'Productos Favoritos',
            },
        ),
        migrations.AlterUniqueTogether(
            name='productofavorito',
            unique_together=set([('usuario', 'producto')]),
        ),
    ]
