# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-14 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0019_auto_20180210_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='descripcion',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='marca',
            name='sitio_web',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Sitio web'),
        ),
    ]
