# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-20 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0012_auto_20180216_1625'),
        ('mercado_vindu', '0022_auto_20180214_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistaUserProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vista de Usuario de un Producto',
                'verbose_name_plural': 'Vistas de Usuarios de Productos',
            },
        ),
        migrations.RemoveField(
            model_name='coleccion',
            name='cant_favoritos',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cant_favoritos',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cant_vistas',
        ),
        migrations.AddField(
            model_name='coleccion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foto360producto',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fotocoleccion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fotolocal',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fotonovedad',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fotoproducto',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='novedad',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='cod_producto',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código de Producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vistauserproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_vista_user', to='mercado_vindu.Producto'),
        ),
        migrations.AddField(
            model_name='vistauserproducto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_vista_user', to='auth_api.UserComprador'),
        ),
    ]
