# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-21 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0012_auto_20180216_1625'),
        ('mercado_vindu', '0023_auto_20180220_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeColeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coleccion_like_coleccion', to='mercado_vindu.Marca')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_like_coleccion', to='auth_api.UserComprador')),
            ],
            options={
                'verbose_name': 'Like de Colección',
                'verbose_name_plural': 'Likes de Colecciones',
            },
        ),
        migrations.AlterUniqueTogether(
            name='likecoleccion',
            unique_together=set([('usuario', 'coleccion')]),
        ),
    ]
