# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-21 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0012_auto_20180216_1625'),
        ('mercado_vindu', '0024_auto_20180221_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeFotoColeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_coleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_like_fotocoleccion', to='mercado_vindu.FotoColeccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_like_fotocoleccion', to='auth_api.UserComprador')),
            ],
            options={
                'verbose_name': 'Like de Foto de Colección',
                'verbose_name_plural': 'Likes de Fotos de Colecciones',
            },
        ),
        migrations.CreateModel(
            name='LikeFotoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_like_fotoproducto', to='mercado_vindu.FotoProducto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_like_fotoproducto', to='auth_api.UserComprador')),
            ],
            options={
                'verbose_name': 'Like de Foto de Producto',
                'verbose_name_plural': 'Likes de Fotos de Productos',
            },
        ),
        migrations.AlterUniqueTogether(
            name='likefotoproducto',
            unique_together=set([('usuario', 'foto_producto')]),
        ),
        migrations.AlterUniqueTogether(
            name='likefotocoleccion',
            unique_together=set([('usuario', 'foto_coleccion')]),
        ),
    ]
