# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-27 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import mercado_vindu.models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0025_auto_20180221_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='ind_oferta',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_oferta_desde',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Oferta desde'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_oferta_hasta',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Oferta hasta'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_oferta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[mercado_vindu.models.validate_non_negative], verbose_name='Precio de oferta'),
        ),
        migrations.AddField(
            model_name='talleproducto',
            name='shop_sku',
            field=models.CharField(default='', max_length=30, verbose_name='ShopSku'),
        ),
        migrations.AddField(
            model_name='talleproducto',
            name='stock',
            field=models.IntegerField(default=0, help_text='El stock del producto', validators=[mercado_vindu.models.validate_non_negative], verbose_name='Stock'),
        ),
    ]
