# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-27 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0026_auto_20180227_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talleproducto',
            name='shop_sku',
            field=models.CharField(blank=True, default=' ', max_length=30, verbose_name='ShopSku'),
        ),
    ]
