# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-05 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0027_auto_20180227_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoria_hijos', to='mercado_vindu.Categoria'),
        ),
    ]
