# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-06 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0012_auto_20180216_1625'),
        ('mercado_vindu', '0028_categoria_padre'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoFaltaStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aticulo_falta_stock', to='mercado_vindu.TalleProducto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_falta_stock', to='auth_api.UserComprador')),
            ],
            options={
                'verbose_name_plural': 'Avisos Falta de Stock',
                'verbose_name': 'Aviso Falta de Stock',
            },
        ),
        migrations.AlterUniqueTogether(
            name='avisofaltastock',
            unique_together=set([('usuario', 'articulo')]),
        ),
    ]
