# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-06 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0030_auto_20180306_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tabla_talles',
            field=models.ImageField(blank=True, null=True, upload_to='images/tabla_talles', verbose_name='Tabla de Talles'),
        ),
    ]
