# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-17 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0031_auto_20180306_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='padre',
            new_name='categoria_padre',
        ),
        migrations.AddField(
            model_name='talleproducto',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talleproducto',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
