# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-22 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import mercado_vindu.models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0032_auto_20180317_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fecha_oferta_desde',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_oferta_hasta',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_oferta',
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_descuento_desde',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Descuento desde'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_descuento_hasta',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Descuento hasta'),
        ),
        migrations.AddField(
            model_name='producto',
            name='porc_descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[mercado_vindu.models.validate_percentaje], verbose_name='Porcentaje de descuento'),
        ),
    ]
