# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-23 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0033_auto_20180522_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='valor_promocion_envio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Importe mínimo de promoción del envío'),
        ),
    ]
