# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-31 01:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mercado_vindu.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0035_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesoBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('precio', 'precio'), ('stock', 'stock')], max_length=42)),
                ('archivo', models.FileField(upload_to=mercado_vindu.helpers.user_directory_path)),
                ('procesado', models.BooleanField(default=False)),
                ('procesado_fecha', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procesobatch_marca', to='mercado_vindu.Marca')),
            ],
            options={
                'verbose_name': 'ProcesoBatch',
                'verbose_name_plural': 'ProcesosBatch',
            },
        ),
    ]
