# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-01 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0008_voucher_importe_voucher'),
        ('mercado_vindu', '0036_procesobatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_deposito', models.CharField(max_length=50, verbose_name='Nombre del depósito')),
                ('ind_depósito_default', models.BooleanField(default=False, verbose_name='Indicador depósito de default')),
                ('contacto_deposito', models.CharField(blank=True, help_text='Nombre y apellido del contacto', max_length=100, null=True, verbose_name='Contacto en el depósito')),
                ('telefono_contacto', models.CharField(blank=True, help_text='Numero telefónico del contacto', max_length=30, null=True, verbose_name='Teléfono del Contacto del depósito')),
                ('calle', models.CharField(help_text='Nombre de la calle', max_length=50, verbose_name='Calle')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('piso', models.CharField(blank=True, max_length=6, null=True, verbose_name='Piso')),
                ('departamento', models.CharField(blank=True, max_length=4, null=True, verbose_name='Departamento')),
                ('provincia', models.CharField(max_length=25, verbose_name='Provincia')),
                ('localidad', models.CharField(max_length=50, verbose_name='Localidad')),
                ('cod_postal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cod_postal_deposito', to='configuraciones.CodigoPostal')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposito_marca', to='mercado_vindu.Marca')),
            ],
            options={
                'verbose_name_plural': 'Depósitos',
                'verbose_name': 'Depósito',
            },
        ),
    ]
