# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-05 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0037_deposito'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='agente_ret_gan',
            field=models.BooleanField(default=False, verbose_name='Agente de retención de Ganancias'),
        ),
        migrations.AddField(
            model_name='marca',
            name='agente_ret_ib',
            field=models.BooleanField(default=False, verbose_name='Agente de retención de Ingresos Brutos'),
        ),
        migrations.AddField(
            model_name='marca',
            name='agente_ret_iva',
            field=models.BooleanField(default=False, verbose_name='Agente de retención de IVA'),
        ),
        migrations.AddField(
            model_name='marca',
            name='cbu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CBU'),
        ),
        migrations.AddField(
            model_name='marca',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='marca',
            name='condicion_iva',
            field=models.CharField(choices=[('RI', 'Responsable Inscripto'), ('RN', 'Responsable No Inscripto'), ('MO', 'Monotributista'), ('EX', 'Exento')], default='RI', max_length=2, verbose_name='Condición ante el IVA'),
        ),
        migrations.AddField(
            model_name='marca',
            name='contrato_firmado',
            field=models.FileField(blank=True, default=None, null=True, upload_to='images/contratos_firmados', verbose_name='Contrato firmado'),
        ),
        migrations.AddField(
            model_name='marca',
            name='cuit_nro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cuit Nro'),
        ),
        migrations.AddField(
            model_name='marca',
            name='domicilio_fiscal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Domicilio Fiscal'),
        ),
        migrations.AddField(
            model_name='marca',
            name='localidad',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='marca',
            name='nro_cuenta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nro de cuenta bancaria'),
        ),
        migrations.AddField(
            model_name='marca',
            name='provincia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='marca',
            name='razon_social',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='marca',
            name='responsable_cobranzas',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsable de cobranzas'),
        ),
        migrations.AddField(
            model_name='marca',
            name='responsable_ventas',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsable de ventas'),
        ),
        migrations.AddField(
            model_name='marca',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de Fantasía'),
        ),
    ]
