# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-11 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0038_auto_20180605_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_post', models.FileField(upload_to='images/media_posteos', verbose_name='Imagen del Posteo')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Imagen del Posteo',
                'verbose_name_plural': 'Imágenes del Posteo',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_post', models.CharField(max_length=255, verbose_name='Nombre del Posteo')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_marca', to='mercado_vindu.Marca')),
            ],
            options={
                'verbose_name': 'Posteo',
                'verbose_name_plural': 'Posteos',
            },
        ),
        migrations.AddField(
            model_name='imagenpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado_vindu.Post'),
        ),
    ]
