# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-12 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0039_auto_20180611_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagen_post', to='mercado_vindu.Post'),
        ),
    ]
