# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-13 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0040_auto_20180612_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposito',
            old_name='ind_depósito_default',
            new_name='ind_deposito_default',
        ),
    ]
