# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-11 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0042_auto_20180705_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesobatch',
            name='procesado_fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
