# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-02 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0012_auto_20180216_1625'),
        ('mercado_vindu', '0049_auto_20180727_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_like_post', to='mercado_vindu.Post')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_like_post', to='auth_api.UserComprador')),
            ],
            options={
                'verbose_name': 'Like de Post',
                'verbose_name_plural': 'Likes de Posts',
            },
        ),
        migrations.AlterUniqueTogether(
            name='likepost',
            unique_together=set([('usuario', 'post')]),
        ),
    ]
