# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-04 23:56
from __future__ import unicode_literals

import core.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0050_auto_20180802_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto_principal',
            field=core.utils.ContentTypeRestrictedImageField(default='images/fotos_productos/Sin_imagen_disponible.jpg', upload_to='images/fotos_productos', verbose_name='Foto Principal'),
        ),
    ]
