# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-07 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0051_auto_20180804_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto_principal_optim',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='images/optim/fotos_productos', verbose_name='Foto Principal Optimizada'),
        ),
        migrations.AddField(
            model_name='producto',
            name='foto_principal_thumb',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='images/thumb/fotos_productos', verbose_name='Foto Principal Thumbnail'),
        ),
    ]
