# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-08 14:38
from __future__ import unicode_literals

from django.db import migrations
from core.utils import ContentTypeRestrictedImageField, ContentTypeRestrictedFileField, \
                       generate_optim_picture, generate_thumb_picture
from django.core.files.base import ContentFile


def generar_optim_thumb_foto_ppal(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    print('entra a generar_optim_thumb')
    Producto = apps.get_model('mercado_vindu', 'Producto')
    for product in Producto.objects.all():
        temp_thumb, filename, file_ext = generate_optim_picture(product.foto_principal)
        # Save image field
        product.foto_principal_optim.save(filename, ContentFile(temp_thumb.read()), save=False)
        temp_thumb.close()
        temp_thumb, filename, file_ext = generate_thumb_picture(product.foto_principal)
        product.foto_principal_thumb.save(filename, ContentFile(temp_thumb.read()), save=False)
        temp_thumb.close()
        product.save()



class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0053_auto_20180808_1136'),
    ]

    operations = [
        migrations.RunPython(generar_optim_thumb_foto_ppal),
    ]
