# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-09 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0054_auto_20180808_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotoproducto',
            name='foto_producto_optim',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='images/fotos_productos/optim', verbose_name='Foto de Producto Optimizada'),
        ),
        migrations.AddField(
            model_name='fotoproducto',
            name='foto_producto_thumb',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='images/fotos_productos/thumb', verbose_name='Foto de Producto Thumbnail'),
        ),
    ]
