# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-09 17:47
from __future__ import unicode_literals

from django.db import migrations
from core.utils import ContentTypeRestrictedImageField, ContentTypeRestrictedFileField, \
                       generate_optim_picture, generate_thumb_picture
from django.core.files.base import ContentFile


def generar_optim_thumb_foto_producto(apps, schema_editor):
    print('entra a generar_optim_thumb')
    FotoProducto = apps.get_model('mercado_vindu', 'FotoProducto')
    for foto_producto in FotoProducto.objects.all():
        temp_thumb, filename, file_ext = generate_optim_picture(foto_producto.foto_producto)
        # Save image field
        foto_producto.foto_producto_optim.save(filename, ContentFile(temp_thumb.read()), save=False)
        temp_thumb.close()
        temp_thumb, filename, file_ext = generate_thumb_picture(foto_producto.foto_producto)
        foto_producto.foto_producto_thumb.save(filename, ContentFile(temp_thumb.read()), save=False)
        temp_thumb.close()
        foto_producto.save()

class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0055_auto_20180809_1446'),
    ]

    operations = [
        migrations.RunPython(generar_optim_thumb_foto_producto),
    ]
