# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-09 18:00
from __future__ import unicode_literals

import core.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0056_auto_20180809_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoproducto',
            name='foto_producto',
            field=core.utils.ContentTypeRestrictedImageField(help_text='Formatos válidos: jpg, jpeg, gif, png', upload_to='images/fotos_productos', verbose_name='Foto del Producto'),
        ),
    ]
