# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-09 20:01
from __future__ import unicode_literals

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0057_auto_20180809_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenpost',
            name='imagen_post_optim',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='images/media_posteos/optim', verbose_name='Imagen del Posteo Optimizada'),
        ),
        migrations.AddField(
            model_name='imagenpost',
            name='imagen_post_thumb',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='images/media_posteos/thumb', verbose_name='Imagen del Posteo Thumbnail'),
        ),
        migrations.AlterField(
            model_name='imagenpost',
            name='imagen_post',
            field=core.utils.ContentTypeRestrictedFileField(help_text='Formatos válidos: jpg, jpeg, gif, png, mp4', upload_to='images/media_posteos', verbose_name='Imagen del Posteo'),
        ),
    ]
