# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-10 18:12
from __future__ import unicode_literals

from django.db import migrations
from core.utils import ContentTypeRestrictedImageField, ContentTypeRestrictedFileField, \
                       generate_optim_picture, generate_thumb_picture
from django.core.files.base import ContentFile
from django.conf import settings


def generar_optim_thumb_imagen_post(apps, schema_editor):
    print('entra a generar_optim_thumb')
    ImagenPost = apps.get_model('mercado_vindu', 'ImagenPost')
    for imagen_post in ImagenPost.objects.all():
        # Chequea si la imagen_post es foto o video - Si es foto genera las versiones optimizadas
        import mimetypes

        file_type = mimetypes.guess_type(imagen_post.imagen_post.url)[0]

        if file_type in settings.PICTURE_TYPES:
            temp_thumb, filename, file_ext = generate_optim_picture(imagen_post.imagen_post)
            # Save image field
            imagen_post.imagen_post_optim.save(filename, ContentFile(temp_thumb.read()), save=False)
            temp_thumb.close()
            temp_thumb, filename, file_ext = generate_thumb_picture(imagen_post.imagen_post)
            imagen_post.imagen_post_thumb.save(filename, ContentFile(temp_thumb.read()), save=False)
            temp_thumb.close()

        imagen_post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0058_auto_20180809_1701'),
    ]

    operations = [
        migrations.RunPython(generar_optim_thumb_imagen_post),        
    ]

