# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-13 20:09
from __future__ import unicode_literals

import core.utils
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0059_auto_20180810_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLinkPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', embed_video.fields.EmbedVideoField(max_length=150, verbose_name='Link de Video')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_link_post', to='mercado_vindu.Post')),
            ],
            options={
                'verbose_name': 'Link de Video del Posteo',
                'verbose_name_plural': 'Links de Video de Posteo',
            },
        ),
        migrations.AlterField(
            model_name='imagenpost',
            name='imagen_post',
            field=core.utils.ContentTypeRestrictedFileField(help_text='Formatos válidos: jpg, jpeg, gif, png', upload_to='images/media_posteos', verbose_name='Imagen del Posteo'),
        ),
    ]
