# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-15 13:53
from __future__ import unicode_literals

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0060_auto_20180813_1709'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likeimagenpost',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='likeimagenpost',
            name='imagen_post',
        ),
        migrations.RemoveField(
            model_name='likeimagenpost',
            name='usuario',
        ),
        migrations.AlterModelOptions(
            name='videolinkpost',
            options={'verbose_name': 'Link de Video', 'verbose_name_plural': 'Links de Video'},
        ),
        migrations.AlterField(
            model_name='videolinkpost',
            name='video_link',
            field=embed_video.fields.EmbedVideoField(help_text='Ingresar Link de Video', max_length=150, verbose_name='Link de Video'),
        ),
        migrations.DeleteModel(
            name='LikeImagenPost',
        ),
    ]
