# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-17 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0061_auto_20180815_1053'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productofavorito',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='productofavorito',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='productofavorito',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='ProductoFavorito',
        ),
    ]
