# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-18 18:58
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('mercado_vindu', '0062_auto_20180817_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
