# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-18 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0063_producto_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagsproducto',
            name='producto',
        ),
        migrations.DeleteModel(
            name='TagsProducto',
        ),
    ]
