# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-28 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0065_marca_proveedor_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaTalles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_prenda', models.CharField(choices=[('PS', 'Prenda superior'), ('PI', 'Prenda inferior'), ('CA', 'Calzado')], max_length=2, verbose_name='Tipo de prenda')),
                ('segmento_sexo', models.CharField(choices=[('HOMBRE', 'Hombre'), ('MUJER', 'Mujer'), ('AMBOS SEXOS', 'Ambos sexos')], default='HOMBRE', max_length=15, verbose_name='Género')),
                ('imagen_talles', models.ImageField(upload_to='images/tabla_talles', verbose_name='Imagen de Talles')),
            ],
            options={
                'verbose_name': 'Tabla de Talles',
                'verbose_name_plural': 'Tablas de Talles',
            },
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='tabla_talles',
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_prenda',
            field=models.CharField(choices=[('PS', 'Prenda superior'), ('PI', 'Prenda inferior'), ('CA', 'Calzado')], default='PS', max_length=2, verbose_name='Tipo de prenda'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='pu_client_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PayU Client Id'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='pu_client_secret',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PayU Client Secret'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='segmento_sexo',
            field=models.CharField(choices=[('HOMBRE', 'Hombre'), ('MUJER', 'Mujer'), ('AMBOS SEXOS', 'Ambos sexos')], default='HOMBRE', max_length=15, verbose_name='Segmento de sexo'),
        ),
        migrations.AlterUniqueTogether(
            name='tablatalles',
            unique_together=set([('tipo_prenda', 'segmento_sexo')]),
        ),
    ]
