# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-28 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0066_auto_20180828_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='segmento_sexo',
            field=models.CharField(choices=[('HOMBRE', 'Hombre'), ('MUJER', 'Mujer')], default='HOMBRE', max_length=15, verbose_name='Segmento de sexo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='tablatalles',
            name='segmento_sexo',
            field=models.CharField(choices=[('HOMBRE', 'Hombre'), ('MUJER', 'Mujer')], default='HOMBRE', max_length=15, verbose_name='Género'),
        ),
    ]
