# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-28 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0067_auto_20180828_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_talles',
            field=models.ImageField(blank=True, null=True, upload_to='images/tabla_talles', verbose_name='Imagen de Talles'),
        ),
    ]
