# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-10 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0068_producto_imagen_talles'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='logo_cuadrado',
            field=models.ImageField(blank=True, help_text='Logo con alto igual a ancho', null=True, upload_to='images/logos', verbose_name='Logo cuadrado'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='logo',
            field=models.ImageField(help_text='Imagen con proporción ancho:alto = 1:0.2037', upload_to='images/logos', verbose_name='Logo banner'),
        ),
    ]
