# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-29 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0070_auto_20180914_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='pu_client_id',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='pu_client_secret',
        ),
        migrations.AddField(
            model_name='marca',
            name='account_id',
            field=models.IntegerField(null=True, verbose_name='PayU Account Id'),
        ),
        migrations.AddField(
            model_name='marca',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PayU Api Key'),
        ),
        migrations.AddField(
            model_name='marca',
            name='api_login',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PayU Api Login'),
        ),
        migrations.AddField(
            model_name='marca',
            name='merchand_id',
            field=models.IntegerField(null=True, verbose_name='PayU Merchand Id'),
        ),
    ]
