# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-29 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0071_auto_20180929_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='account_id',
            new_name='pu_account_id',
        ),
        migrations.RenameField(
            model_name='marca',
            old_name='api_key',
            new_name='pu_api_key',
        ),
        migrations.RenameField(
            model_name='marca',
            old_name='api_login',
            new_name='pu_api_login',
        ),
        migrations.RenameField(
            model_name='marca',
            old_name='merchand_id',
            new_name='pu_merchand_id',
        ),
    ]
