# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-05 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0073_auto_20180929_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='TomaFoto360',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_secuencia', models.IntegerField(default=0, help_text='Dejar en blanco para asignación automática', verbose_name='Nro de secuencia')),
                ('foto360_imagen', models.ImageField(upload_to='images/fotos360_productos', verbose_name='Toma de Foto 360 del Producto')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Tomas de Fotos 360 del Producto',
                'verbose_name': 'Toma de Foto 360 del Producto',
            },
        ),
        migrations.RemoveField(
            model_name='foto360producto',
            name='foto360_producto',
        ),
        migrations.AddField(
            model_name='foto360producto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='tomafoto360',
            name='foto360',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toma_rel_foto360', to='mercado_vindu.Foto360Producto'),
        ),
    ]
