# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-06 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0074_auto_20181005_1619'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcercaVindu',
        ),
        migrations.DeleteModel(
            name='CambiosYDevoluciones',
        ),
        migrations.DeleteModel(
            name='CuotasFormaPago',
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='PoliticasPrivacidad',
        ),
        migrations.DeleteModel(
            name='TerminosCondiciones',
        ),
        migrations.DeleteModel(
            name='TiempoCostoEnvio',
        ),
    ]
