# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-08 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0075_auto_20181006_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tomafoto360',
            name='nro_secuencia',
        ),
    ]
