# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-20 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrito', '0020_auto_20180918_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoMercadoPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('transaction_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('external_resource_url', models.CharField(blank=True, max_length=250, null=True)),
                ('payment_method_reference_id', models.CharField(blank=True, max_length=250, null=True)),
                ('financial_institution', models.CharField(blank=True, max_length=250, null=True)),
                ('installment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_received_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('overpaid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transaction_amount_refunded', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payer_first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('payer_last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('payer_entity_type', models.CharField(blank=True, max_length=150, null=True)),
                ('payer_id', models.CharField(blank=True, max_length=150, null=True)),
                ('payer_phone_area_code', models.CharField(blank=True, max_length=150, null=True)),
                ('payer_phone_number', models.CharField(blank=True, max_length=150, null=True)),
                ('payer_phone_extension', models.CharField(blank=True, max_length=150, null=True)),
                ('payer_identification_type', models.CharField(blank=True, max_length=150, null=True)),
                ('payer_identification_number', models.CharField(blank=True, max_length=150, null=True)),
                ('payer_type', models.CharField(blank=True, max_length=150, null=True)),
                ('payer_email', models.CharField(blank=True, max_length=150, null=True)),
                ('currency_id', models.CharField(blank=True, max_length=150, null=True)),
                ('issuer_id', models.CharField(blank=True, max_length=150, null=True)),
                ('statement_descriptor', models.CharField(blank=True, max_length=150, null=True)),
                ('captured', models.NullBooleanField()),
                ('date_approved', models.CharField(blank=True, max_length=150, null=True)),
                ('money_release_date', models.CharField(blank=True, max_length=150, null=True)),
                ('notification_url', models.CharField(blank=True, max_length=150, null=True)),
                ('_id', models.CharField(blank=True, max_length=150, null=True)),
                ('collector_id', models.CharField(blank=True, max_length=150, null=True)),
                ('payment_type_id', models.CharField(blank=True, max_length=150, null=True)),
                ('differential_pricing_id', models.IntegerField(blank=True, null=True)),
                ('live_mode', models.NullBooleanField()),
                ('payment_method_id', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(blank=True, max_length=150, null=True)),
                ('date_last_updated', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('authorization_code', models.CharField(blank=True, max_length=150, null=True)),
                ('status_detail', models.CharField(blank=True, max_length=150, null=True)),
                ('operation_type', models.CharField(blank=True, max_length=150, null=True)),
                ('coupon_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('binary_mode', models.NullBooleanField()),
                ('card_last_four_digits', models.CharField(blank=True, max_length=150, null=True)),
                ('card_date_last_updated', models.CharField(blank=True, max_length=150, null=True)),
                ('card_expiration_year', models.IntegerField(blank=True, null=True)),
                ('card_expiration_month', models.IntegerField(blank=True, null=True)),
                ('card_cardholder_identification_type', models.CharField(blank=True, max_length=150, null=True)),
                ('card_cardholder_identification_number', models.CharField(blank=True, max_length=150, null=True)),
                ('card_cardholder_name', models.CharField(blank=True, max_length=150, null=True)),
                ('card_date_created', models.CharField(blank=True, max_length=150, null=True)),
                ('card_first_six_digits', models.CharField(blank=True, max_length=150, null=True)),
                ('card_id', models.IntegerField(blank=True, null=True)),
                ('external_reference', models.CharField(blank=True, max_length=150, null=True)),
                ('call_for_authorize_id', models.CharField(blank=True, max_length=150, null=True)),
                ('installments', models.IntegerField(blank=True, null=True)),
                ('date_created', models.CharField(blank=True, max_length=150, null=True)),
                ('message', models.CharField(blank=True, max_length=150, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_pago_mercadopago', to='carrito.Pedido')),
            ],
            options={
                'verbose_name': 'Pago MercadoPago',
                'verbose_name_plural': 'Pagos MercadoPago',
            },
        ),
    ]
