# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 18:03
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_auto_20180108_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComprador',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('foto_avatar', models.ImageField(upload_to='images/fotos_avatares', verbose_name='Avatar')),
                ('facebook_id', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name_plural': 'Usuarios Compradores',
                'verbose_name': 'Usuario Comprador',
            },
            bases=('auth_api.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
