# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0003_usercomprador'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomprador',
            name='dob',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usercomprador',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True, verbose_name='Género'),
        ),
    ]
