# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0006_auto_20180125_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomprador',
            name='dob',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
