# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0008_auto_20180205_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioSeguido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_usuario_seguidor', to='auth_api.UserComprador')),
                ('usuario_seguido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_usuario_seguido', to='auth_api.UserComprador')),
            ],
            options={
                'verbose_name_plural': 'Usuarios Seguidos',
                'verbose_name': 'Usuario Seguido',
            },
        ),
        migrations.AlterUniqueTogether(
            name='usuarioseguido',
            unique_together=set([('usuario', 'usuario_seguido')]),
        ),
    ]
