# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-16 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0011_auto_20180215_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomprador',
            name='wishlist_visible',
        ),
        migrations.AddField(
            model_name='usercomprador',
            name='wishlist_publico',
            field=models.BooleanField(default=True, verbose_name='WishList público'),
        ),
    ]
