# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-18 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0012_auto_20180216_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomprador',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
