# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-18 18:49
from __future__ import unicode_literals

import configuraciones.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoPostalZona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_postal', models.IntegerField(verbose_name='Código Postal')),
                ('provincia', models.CharField(max_length=25, verbose_name='Provincia')),
                ('codigo_region', models.CharField(max_length=4, verbose_name='Código de región')),
                ('municipio', models.CharField(max_length=50, verbose_name='Código de región')),
                ('localidad', models.CharField(max_length=50, verbose_name='Localidad')),
            ],
            options={
                'verbose_name': 'Código Postal por Zona',
                'verbose_name_plural': 'Códigos Postales por Zona',
            },
        ),
        migrations.CreateModel(
            name='DescuentoPrimeraCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe_fijo_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Importe fijo de descuento por primera compra')),
                ('dias_vigencia_descuento', models.IntegerField(default=0, help_text='Cantidad de días contando desde la registración del usuario', validators=[configuraciones.models.validate_non_negative], verbose_name='Días de vigencia del descuento')),
            ],
            options={
                'verbose_name': 'Descuento por primera compra',
            },
        ),
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('identificador', models.CharField(max_length=20, verbose_name='Identificador')),
                ('comision', models.DecimalField(decimal_places=2, default=0, help_text='Ej: 5 (para 5%)', max_digits=10, verbose_name='Porcentaje de comision')),
                ('precio_en_dolares', models.BooleanField(default=False, help_text='Se debe convertir el precio a dolares', verbose_name='Precio en dolares')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, default=None, upload_to='imagenes_medios_de_pago')),
            ],
            options={
                'verbose_name': 'Medio de Pago',
                'verbose_name_plural': 'Medios de Pago',
            },
        ),
        migrations.CreateModel(
            name='TarifaZonaEnvio',
            fields=[
                ('id_zona', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la zona')),
                ('nombre_zona', models.CharField(max_length=20, verbose_name='Nombre de la zona')),
                ('tarifa_hasta_1', models.DecimalField(decimal_places=2, help_text='Tarifa hasta 1 Kg', max_digits=15, validators=[configuraciones.models.validate_non_negative], verbose_name='Tarifa hasta 1 Kg')),
                ('tarifa_hasta_3', models.DecimalField(decimal_places=2, help_text='Tarifa hasta 3 Kg', max_digits=15, validators=[configuraciones.models.validate_non_negative], verbose_name='Tarifa hasta 3 Kg')),
                ('tarifa_hasta_5', models.DecimalField(decimal_places=2, help_text='Tarifa hasta 5 Kg', max_digits=15, validators=[configuraciones.models.validate_non_negative], verbose_name='Tarifa hasta 5 Kg')),
                ('tarifa_hasta_10', models.DecimalField(decimal_places=2, help_text='Tarifa hasta 10 Kg', max_digits=15, validators=[configuraciones.models.validate_non_negative], verbose_name='Tarifa hasta 10 Kg')),
            ],
            options={
                'verbose_name': 'Tarifas para Zona de Envío',
                'verbose_name_plural': 'Tarifas para Zonas de Envíos',
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_voucher', models.CharField(max_length=20, unique=True, verbose_name='Código de Voucher')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('fecha_vigencia_desde', models.DateField(verbose_name='Fecha de vigencia desde')),
                ('fecha_vigencia_hasta', models.DateField(verbose_name='Fecha de vigencia hasta')),
                ('importe_minimo_compra', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Importe mínimo de compra')),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Vouchers',
            },
        ),
        migrations.AddField(
            model_name='codigopostalzona',
            name='zona_tarifa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.TarifaZonaEnvio'),
        ),
    ]
