# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-18 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
        ('auth_api', '0012_auto_20180216_1625'),
        ('configuraciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherUsado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedido_voucher_usado', to='carrito.Pedido')),
                ('usuario_comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_voucher_usado', to='auth_api.UserComprador')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_voucher_usado', to='configuraciones.Voucher')),
            ],
            options={
                'verbose_name': 'Voucher Utilizado',
                'verbose_name_plural': 'Vouchers Utilizados',
            },
        ),
    ]
