# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-21 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0002_voucherusado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigopostalzona',
            name='codigo_region',
        ),
        migrations.RemoveField(
            model_name='codigopostalzona',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='codigopostalzona',
            name='municipio',
        ),
    ]
