# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-21 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0003_auto_20180521_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigopostalzona',
            name='id',
        ),
        migrations.AlterField(
            model_name='codigopostalzona',
            name='cod_postal',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Código Postal'),
        ),
    ]
