# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-21 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_remove_domicilio_cod_postal_zona'),
        ('configuraciones', '0004_auto_20180521_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoPostalProvincia',
            fields=[
                ('cod_postal', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código Postal')),
                ('provincia', models.CharField(max_length=25, verbose_name='Provincia')),
            ],
            options={
                'verbose_name_plural': 'Códigos Postales y Provincias',
                'verbose_name': 'Código Postal y Provincia',
            },
        ),
        migrations.CreateModel(
            name='MunicipioLocalidadZonaTarifa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=50, verbose_name='Municipio')),
                ('localidad', models.CharField(max_length=50, verbose_name='Localidad')),
                ('cod_postal_provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.CodigoPostalProvincia')),
                ('zona_tarifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.TarifaZonaEnvio')),
            ],
            options={
                'verbose_name_plural': 'Municipios, Localidades y Tarifas de Zona',
                'verbose_name': 'Municipio, Localidad y Tarifa de Zona',
            },
        ),
        migrations.RemoveField(
            model_name='codigopostalzona',
            name='zona_tarifa',
        ),
        migrations.DeleteModel(
            name='CodigoPostalZona',
        ),
    ]
