# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-21 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0004_remove_domicilio_tarifa_zona'),
        ('configuraciones', '0005_auto_20180521_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoPostal',
            fields=[
                ('cod_postal', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código Postal')),
            ],
            options={
                'verbose_name_plural': 'Códigos Postales',
                'verbose_name': 'Código Postal',
            },
        ),
        migrations.CreateModel(
            name='ProvinciaLocalidadZonaTarifa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(max_length=25, verbose_name='Provincia')),
                ('municipio', models.CharField(max_length=50, verbose_name='Municipio')),
                ('localidad', models.CharField(max_length=50, verbose_name='Localidad')),
                ('cod_postal_provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.CodigoPostal')),
                ('zona_tarifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuraciones.TarifaZonaEnvio')),
            ],
            options={
                'verbose_name_plural': 'Provincias, Municipios, Localidades y Tarifas de Zona',
                'verbose_name': 'Provincia, Municipio, Localidad y Tarifa de Zona',
            },
        ),
        migrations.RemoveField(
            model_name='municipiolocalidadzonatarifa',
            name='cod_postal_provincia',
        ),
        migrations.RemoveField(
            model_name='municipiolocalidadzonatarifa',
            name='zona_tarifa',
        ),
        migrations.DeleteModel(
            name='CodigoPostalProvincia',
        ),
        migrations.DeleteModel(
            name='MunicipioLocalidadZonaTarifa',
        ),
    ]
