# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-24 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0006_auto_20180521_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucherusado',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='voucherusado',
            name='usuario_comprador',
        ),
        migrations.RemoveField(
            model_name='voucherusado',
            name='voucher',
        ),
        migrations.DeleteModel(
            name='VoucherUsado',
        ),
    ]
