# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-24 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0007_auto_20180524_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='importe_voucher',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Importe de descuento del voucher'),
        ),
    ]
