# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-28 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0008_voucher_importe_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifazonaenvio',
            name='plazo_entrega',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Plazo de entrega'),
        ),
    ]
