# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-06 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0009_tarifazonaenvio_plazo_entrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcercaVindu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_html', models.TextField(verbose_name='Texto HTML')),
            ],
            options={
                'verbose_name_plural': 'Acerca de Vindu',
                'verbose_name': 'Acerca de Vindu',
            },
        ),
        migrations.CreateModel(
            name='CambiosYDevoluciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_html', models.TextField(verbose_name='Texto HTML')),
            ],
            options={
                'verbose_name_plural': 'Cambios y Devoluciones',
                'verbose_name': 'Cambios y Devoluciones',
            },
        ),
        migrations.CreateModel(
            name='CuotasFormaPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_html', models.TextField(verbose_name='Texto HTML')),
            ],
            options={
                'verbose_name_plural': 'Cuotas y Formas de Pago',
                'verbose_name': 'Cuotas y Formas de Pago',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_html', models.TextField(verbose_name='Texto HTML')),
            ],
            options={
                'verbose_name_plural': 'FAQ',
                'verbose_name': 'FAQ',
            },
        ),
        migrations.CreateModel(
            name='PoliticasPrivacidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_html', models.TextField(verbose_name='Texto HTML')),
            ],
            options={
                'verbose_name_plural': 'Políticas de Privacidad',
                'verbose_name': 'Políticas de Privacidad',
            },
        ),
        migrations.CreateModel(
            name='TerminosCondiciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_html', models.TextField(verbose_name='Texto HTML')),
            ],
            options={
                'verbose_name_plural': 'Términos y Condiciones',
                'verbose_name': 'Términos y Condiciones',
            },
        ),
        migrations.CreateModel(
            name='TiempoCostoEnvio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_html', models.TextField(verbose_name='Texto HTML')),
            ],
            options={
                'verbose_name_plural': 'Tiempos y Costos de Envío',
                'verbose_name': 'Tiempo y Costo de Envío',
            },
        ),
    ]
