# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-03 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mercado_vindu', '0073_auto_20180929_1838'),
        ('carrito', '0023_auto_20180929_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obligacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deudor', models.CharField(choices=[('M', 'Marca'), ('V', 'Vindu')], max_length=1, verbose_name='Deudor')),
                ('acreedor', models.CharField(choices=[('M', 'Marca'), ('V', 'Vindu')], max_length=1, verbose_name='Acreedor')),
                ('importe_adeudado', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Importe adeudado')),
                ('estado_liquidacion', models.BooleanField(default=False, verbose_name='Estado de liquidación')),
                ('fecha_liquidacion', models.DateTimeField(verbose_name='Fecha y hora de liquidación')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('marca_acreedora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obligacion_marca_acreedora', to='mercado_vindu.Marca')),
                ('marca_deudora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obligacion_marca_deudora', to='mercado_vindu.Marca')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligacion_pedido', to='carrito.Pedido')),
            ],
        ),
    ]
