# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-03 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obligaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obligacion',
            name='fecha_liquidacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de liquidación'),
        ),
    ]
