# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-03 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obligaciones', '0002_auto_20181003_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obligacion',
            options={'verbose_name': 'Obligación', 'verbose_name_plural': 'Obligaciones'},
        ),
        migrations.AddField(
            model_name='obligacion',
            name='concepto',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Concepto'),
        ),
    ]
