# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-18 18:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_api', '0012_auto_20180216_1625'),
        ('mercado_vindu', '0032_auto_20180317_1247'),
        ('configuraciones', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido')),
                ('calle', models.CharField(blank=True, max_length=50, null=True, verbose_name='Calle')),
                ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('piso', models.CharField(blank=True, max_length=6, null=True, verbose_name='Piso')),
                ('departamento', models.CharField(blank=True, max_length=4, null=True, verbose_name='Departamento')),
                ('cod_postal_zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domicilio_cod_postal', to='configuraciones.CodigoPostalZona')),
                ('usuario_comprador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domicilio_user_comprador', to='auth_api.UserComprador')),
            ],
            options={
                'verbose_name': 'Domicilio',
                'verbose_name_plural': 'Domicilios',
            },
        ),
        migrations.CreateModel(
            name='LineaPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado_vindu.TalleProducto')),
            ],
            options={
                'verbose_name': 'Línea de Pedido',
                'verbose_name_plural': 'Líneas de Pedido',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('nro_pedido', models.AutoField(primary_key=True, serialize=False, verbose_name='Número de Pedido')),
                ('importe_pedido', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Importe del Pedido')),
                ('importe_descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Importe de descuentos')),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Importe Total del Pedido con descuentos')),
                ('estado_pedido', models.CharField(choices=[('P', 'Pendiente de entrega'), ('E', 'Entregado')], default='P', max_length=1, verbose_name='Estado del Pedido')),
                ('fecha_pedido', models.DateField(default=datetime.date.today, verbose_name='Fecha de confección del Pedido')),
                ('fecha_pedido_entregado', models.DateField(blank=True, null=True, verbose_name='Fecha en que el pedido fue entregado')),
                ('comision_vindu', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Importe de comisión Vindu')),
                ('flag_regalo', models.BooleanField(default=False, verbose_name='Es un regalo?')),
                ('telefono_contacto', models.CharField(blank=True, max_length=25, null=True, verbose_name='Teléfono de contacto')),
                ('fecha_solicitada_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha solicitada de entrega')),
                ('comentarios_pedido', models.TextField(blank=True, max_length=150, null=True, verbose_name='Comentarios sobre el pedido')),
                ('cargo_costo_envio', models.CharField(blank=True, choices=[('A', 'Costo de envío a cargo de Anting'), ('M', 'Costo de envío a cargo de la Marca')], max_length=1, null=True, verbose_name='Cargo costo del envio')),
                ('costo_envio', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Costo del envío')),
                ('estado_pago', models.CharField(choices=[('PEN', 'Pendiente de pago'), ('PAG', 'Pagado')], default='PEN', max_length=3, verbose_name='Estado del pago')),
                ('domicilio_envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_dom_envio', to='carrito.Domicilio')),
                ('domicilio_facturacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_dom_facturacion', to='carrito.Domicilio')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado_vindu.Marca')),
                ('usuario_comprador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedido_user_comprador', to='auth_api.UserComprador')),
                ('usuario_receptor_regalo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedido_user_regalado', to='auth_api.UserComprador')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.Pedido'),
        ),
    ]
