# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-21 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domicilio',
            name='cod_postal_zona',
        ),
    ]
