# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-21 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0005_auto_20180521_1305'),
        ('carrito', '0002_remove_domicilio_cod_postal_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicilio',
            name='tarifa_zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='domicilio_tarifa_zona', to='configuraciones.MunicipioLocalidadZonaTarifa'),
        ),
    ]
