# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-21 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_domicilio_tarifa_zona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domicilio',
            name='tarifa_zona',
        ),
    ]
