# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-21 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0004_remove_domicilio_tarifa_zona'),
        ('configuraciones', '0006_auto_20180521_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicilio',
            name='cod_postal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='domicilio_tarifa_zona', to='configuraciones.CodigoPostal'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='zona_tarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedido_tarifa_zona', to='configuraciones.ProvinciaLocalidadZonaTarifa'),
        ),
    ]
