# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-22 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0005_auto_20180521_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicilio',
            name='localidad',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='provincia',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Provincia'),
        ),
    ]
