# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-24 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0007_auto_20180524_1053'),
        ('carrito', '0006_auto_20180522_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='voucher_aplicado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedido_voucher_aplicado', to='configuraciones.Voucher'),
        ),
    ]
