# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-01 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0008_auto_20180531_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuento',
            name='motivo_descuento',
            field=models.CharField(max_length=50, verbose_name='Motivo del descuento'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(choices=[('I', 'Pendiente de pago'), ('P', 'Pendiente de entrega'), ('E', 'Entregado'), ('C', 'Cancelado'), ('D', 'Devuelto')], default='I', max_length=1, verbose_name='Estado del Pedido'),
        ),
    ]
