# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-04 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0010_pedido_deposito_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='entre_1',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Calle lateral 1 o intersección de destinatario'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='entre_2',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Calle lateral 2'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono de contacto'),
        ),
    ]
