# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-30 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0013_auto_20180608_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comprobante_mercadopago',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de pago del Pedido'),
        ),
    ]
