# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-02 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0014_auto_20180630_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='importe_pedido',
        ),
    ]
