# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-02 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0015_remove_pedido_importe_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='importe_total',
        ),
    ]
