# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-04 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0012_auto_20180216_1625'),
        ('mercado_vindu', '0068_producto_imagen_talles'),
        ('carrito', '0016_remove_pedido_importe_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('usuario_comprador', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='carrito_user_comprador', serialize=False, to='auth_api.UserComprador')),
            ],
            options={
                'verbose_name_plural': 'Carritos de Compras',
                'verbose_name': 'Carrito de Compras',
            },
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado_vindu.TalleProducto')),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito_linea_carrito', to='carrito.Carrito')),
            ],
            options={
                'verbose_name_plural': 'Items del Carrito',
                'verbose_name': 'Item del Carrito',
            },
        ),
    ]
