# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-14 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0008_voucher_importe_voucher'),
        ('carrito', '0018_auto_20180904_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domicilio',
            name='localidad',
        ),
        migrations.AddField(
            model_name='domicilio',
            name='localidad_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuraciones.ProvinciaLocalidadZonaTarifa'),
        ),
    ]
