# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-18 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0019_auto_20180914_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='domicilio_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedido_dom_envio', to='carrito.Domicilio'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='domicilio_facturacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedido_dom_facturacion', to='carrito.Domicilio'),
        ),
    ]
