# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-24 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0020_auto_20180918_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineapedido',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mercado_vindu.TalleProducto'),
        ),
        migrations.AlterField(
            model_name='lineapedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articulos_pedido', to='carrito.Pedido'),
        ),
    ]
