# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-25 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0021_auto_20180924_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='url_pago_MP',
            field=models.URLField(blank=True, null=True, verbose_name='Init point MP'),
        ),
    ]
