# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-10 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercado_vindu', '0076_remove_tomafoto360_nro_secuencia'),
        ('auth_api', '0012_auto_20180216_1625'),
        ('configuraciones', '0010_acercavindu_cambiosydevoluciones_cuotasformapago_faq_politicasprivacidad_terminoscondiciones_tiempoc'),
        ('carrito', '0023_auto_20180929_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='domicilio_envio',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='domicilio_facturacion',
        ),
        migrations.AddField(
            model_name='carrito',
            name='cargo_costo_envio',
            field=models.CharField(choices=[('A', 'Costo de envío a cargo de Anting'), ('M', 'Costo de envío a cargo de la Marca')], default='A', max_length=1, verbose_name='Cargo costo del envio'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='comentarios_pedido',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Comentarios sobre el pedido'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='comision_vindu',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Importe de comisión Vindu'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='costo_envio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Costo del envío'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='deposito_marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carrito_deposito_marca', to='mercado_vindu.Deposito'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='domicilio_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carrito_dom_envio', to='carrito.Domicilio'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='domicilio_facturacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carrito_dom_facturacion', to='carrito.Domicilio'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='entre_1',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Calle lateral 1 o intersección de destinatario'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='entre_2',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Calle lateral 2'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='fecha_solicitada_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha solicitada de entrega'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='flag_regalo',
            field=models.BooleanField(default=False, verbose_name='Es un regalo?'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='importe_descuentos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Importe de descuentos'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='responsable_envio',
            field=models.CharField(choices=[('A', 'Anting'), ('I', 'IFlow')], default='A', max_length=1, verbose_name='Responsable del envio'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono de contacto'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='usuario_receptor_regalo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carrito_user_regalado', to='auth_api.UserComprador'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='voucher_aplicado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carrito_voucher_aplicado', to='configuraciones.Voucher'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='zona_tarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carrito_tarifa_zona', to='configuraciones.ProvinciaLocalidadZonaTarifa'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='env_apellido',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='env_calle',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Calle'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='env_cod_postal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='env_domicilio_tarifa_zona', to='configuraciones.CodigoPostal'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='env_departamento',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='env_localidad_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='env_localidad_ref', to='configuraciones.ProvinciaLocalidadZonaTarifa'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='env_nombre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='env_numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='env_piso',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Piso'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='env_provincia',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fac_apellido',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fac_calle',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Calle'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fac_cod_postal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fac_domicilio_tarifa_zona', to='configuraciones.CodigoPostal'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fac_departamento',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fac_localidad_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fac_localidad_ref', to='configuraciones.ProvinciaLocalidadZonaTarifa'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fac_nombre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fac_numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fac_piso',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Piso'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fac_provincia',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Provincia'),
        ),
    ]
