# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-10 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0024_auto_20181010_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='comision_vindu',
        ),
    ]
