# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-11 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0025_remove_carrito_comision_vindu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrito',
            name='precio',
        ),
    ]
