# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-12 20:29
from __future__ import unicode_literals

from django.db import migrations


def borrar_pedidos(apps, schema_editor):
    # We can't import the model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    LineaPedido = apps.get_model('carrito', 'LineaPedido')
    LineaPedido.objects.all().delete()

    Descuento = apps.get_model('carrito', 'Descuento')
    Descuento.objects.all().delete()

    Pedido = apps.get_model('carrito', 'Pedido')
    Pedido.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0027_carrito_importe_dto_primera_compra'),
    ]

    operations = [
        migrations.RunPython(borrar_pedidos),
    ]
